spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tonguetwister?useSSL=false
    username: root
    password: root
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #显示sql语句
    show-sql: true
    hibernate:
    #自动建表
      ddl-auto: update
